SELECT
	99999 as CustomerKey,
	26 as GeographyKey,
	'AW00099999' as CustomerAlternateKey,
	NULL as Title,
	'ThisNameIsWayToLongForOurDestinationBecauseItIsGreaterThan50Characters' as FirstName,
	NULL as MiddleName,
	'Doe' as LastName,
	0 as NameStyle,
	NULL as Suffix,
	'1965-08-15' as BirthDate,
	'M' as MaritalStatus,
	'M' as Gender,
	2 as TotalChildren,
	3 as NumberChildrenAtHome,
	'nametoolong@adventure-works.com' as EmailAddress,
	1 as HouseOwnerFlag,
	1 as NumberCarsOwned,
	'111 Test Ave.' as AddressLine1,
	NULL as AddressLine2,
	'1(11) 500 555-0101' as Phone,
	'2001-07-21' as DateFirstPurchased,
	'1-2 Miles' as CommuteDistance,
	'Bachelors' as EnglishEducation,
	'Professional' as EnglishOccupation